/*
See the LICENSE file for this project's licensing information.

Abstract:
A SwiftUI view that shows the cocktail generated by Foundation Models.
*/

import SwiftUI

struct GeneratedCocktail: View {
    @Environment(\.router) private var router
    @Environment(GenerableModel.self) private var model
    
    var body: some View {
        @Bindable var model = model
        
        ScrollView {
            VStack(alignment: .leading, spacing: 0) {
                HeaderMesh()
                    .overlay(alignment: .center) {
                        TitleHeader()
                            .foregroundStyle(.white)
                            .padding(.horizontal)
                    }
                if model.cocktailIdea != nil {
                    VStack(spacing: 20) {
                        InfosCard()
                        
                        if model.showButtons {
                            makeItYoursButton(model: model)
                            iDontLikeItButton
                        }
                    }
                    .animation(.easeIn, value: model.showButtons)
                    .padding(.vertical, 24)
                    .background(.regularMaterial, in: RoundedRectangle(cornerRadius: BarTinderApp.CornerRadius.main))
                    .padding(.horizontal)
                    .offset(y: -60)
                }
            }
        }
        .navigationBarBackButtonHidden()
        .ignoresSafeArea()
        .background(gardientTransition)
        .task {
            if model.cocktailIdea == nil {
                await model.generate()
            }
        }
    }
}

#Preview(traits: .barTinderEnvironments) {
    GeneratedCocktail()
}



extension GeneratedCocktail {
    private func makeItYoursButton(model: GenerableModel) -> some View {
        Button("Make it yours", systemImage: "plus.circle.fill") {
            if let cocktail = model.createCocktail() {
                router.presentSheet(.cocktailDetail(cocktail))
            }
        }
        .buttonStyle(GenerateButton(color: .blue))
        .fontWeight(.semibold)
    }
    
    private var iDontLikeItButton: some View {
        Button("I don't like it", systemImage: "xmark.diamond") {
            router.dismissSheet()
            model.showButtons = false
        }
        .buttonStyle(GenerateButton(color: .red))
        .fontWeight(.semibold)
    }
    
    private var gardientTransition: some View {
        LinearGradient(
            stops: [
                .init(color: .purple.opacity(0.1), location: 0.0),
                .init(color: .purple.opacity(0.05), location: 0.9),
                .init(color: .clear, location: 1.0)
            ],
            startPoint: .top,
            endPoint: .bottom
        )
    }
}

private struct TitleHeader: View {
    @Environment(GenerableModel.self) private var model
    
    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            if let cocktailName = model.cocktailIdea?.content.name {
                Text(cocktailName)
                    .font(.system(size: 28, weight: .bold, design: .rounded))
                    .lineLimit(2)
                    .fixedSize(horizontal: false, vertical: true)
            } else {
                HStack(alignment: .top) {
                    Image(systemName: "sparkles")
                    Text("Crafting the best cocktail that fits your idea...")
                }
                .font(.system(size: 28, weight: .bold, design: .rounded))
            }
            if let cocktailDescription = model.cocktailIdea?.content.description {
                Text(cocktailDescription)
                    .font(.system(size: 15, weight: .regular, design: .default))
                    .lineLimit(4)
                    .fixedSize(horizontal: false, vertical: true)
                    .opacity(0.9)
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
    }
}
