/*
 See the LICENSE file for this project's licensing information.
 
 Abstract:
 A SwiftUI view that shows the cocktail generated by Foundation Models.
 */

import SwiftUI

struct GeneratedCocktail: View {
    @Environment(\.router) private var router
    @Environment(GenerableModel.self) private var model
    
    var body: some View {
        @Bindable var model = model
        
        ScrollView {
            VStack(alignment: .leading, spacing: 0) {
                HeaderMesh()
                    .overlay(alignment: .center) {
                        TitleHeader()
                            .foregroundStyle(.white)
                            .padding(.horizontal)
                    }
                if model.cocktailIdea != nil {
                    VStack(spacing: 20) {
                        InfosCard()
                        
                        if model.showButtons {
                            Group {
                                makeItYoursButton(model: model)
                                iDontLikeItButton
                            }
                            .padding(.horizontal)
                        }
                            
                    }
                    .animation(.easeIn, value: model.showButtons)
                    .padding(.vertical, 24)
                    .background(.regularMaterial, in: RoundedRectangle(cornerRadius: BarTinderApp.CornerRadius.main))
                    .padding(.horizontal)
                    .offset(y: -60)
                }
            }
        }
        .navigationBarBackButtonHidden()
        .ignoresSafeArea()
        .background(gardientTransition)
        .task {
            if model.cocktailIdea == nil {
                await model.generate()
            }
        }
    }
}


#Preview(traits: .modelsEnvironment) {
    GeneratedCocktail()
}


/// Small UI components 
extension GeneratedCocktail {
    private func makeItYoursButton(model: GenerableModel) -> some View {
        Button("Make it yours", systemImage: "plus.circle.fill") {
            if let cocktail = model.createCocktail() {
                router.presentSheet(.cocktailDetail(cocktail))
            }
        }
        .buttonStyle(GenerateButtonStyle(color: .blue))
        .fontWeight(.semibold)
    }
    
    private var iDontLikeItButton: some View {
        Button("I don't like it", systemImage: "xmark.diamond") {
            router.dismissSheet()
            model.showButtons = false
        }
        .buttonStyle(GenerateButtonStyle(color: .red))
        .fontWeight(.semibold)
    }
    
    private var gardientTransition: some View {
        LinearGradient(
            stops: [
                .init(color: .purple.opacity(0.1), location: 0.0),
                .init(color: .purple.opacity(0.05), location: 0.9),
                .init(color: .clear, location: 1.0)
            ],
            startPoint: .top,
            endPoint: .bottom
        )
    }
}

