/*
See the LICENSE file for this project's licensing information.

Abstract:
A use case that creates a cocktail as a persistent model with the idea generated by Apple Intelligence.
*/

import Foundation
import FoundationModels

final class GenerableCreateUseCase {
    func execute(_ cocktailIdea: LanguageModelSession.ResponseStream<CocktailIdea>.Snapshot?) -> Cocktail? {
        var finalIngredients: [Ingredient] = []
        
        guard let name = cocktailIdea?.content.name else { return nil }
        guard let description = cocktailIdea?.content.description else { return nil }
        guard let ingredients = cocktailIdea?.content.ingredients else { return nil }
        let style = cocktailIdea?.content.style.flatMap { CocktailStyle(rawValue: $0) } ?? .shortDrink
        let glass = cocktailIdea?.content.glass.flatMap { CocktailGlass(rawValue: $0) } ?? .highball
        let mixingTechnique = cocktailIdea?.content.mixingTechnique.flatMap { CocktailMixingTechnique(rawValue: $0) } ?? .built
        let difficulty = cocktailIdea?.content.difficulty.flatMap { CocktailDifficulty(rawValue: $0) } ?? .easy
        
        for ingrdt in ingredients {
            guard let ingredientName = ingrdt.name else { return nil }
            guard let ingredientMeasure = ingrdt.amount else { return nil }
            guard let ingredientUnit = Units(rawValue: ingrdt.unit ?? "cl") else { return nil }
            
            let newIngredient = Ingredient(name: ingredientName, measure: String(ingredientMeasure), unit: ingredientUnit)
            finalIngredients.append(newIngredient)
        }
        return Cocktail(
            name: name,
            ingredients: finalIngredients,
            isPossible: true,
            style: style,
            glass: glass,
            mixingTechnique: mixingTechnique,
            difficulty: difficulty,
            cocktailDescription: description
        )
    }
}
