/*
See the LICENSE.txt file for this sample's licensing information.

Abstract:
A use case that creates a cocktail as a persistent model with the idea generated by Apple Intelligence.
*/

import Foundation
import FoundationModels

final class GenerableCreateUseCase {
    func execute(_ cocktailIdea: LanguageModelSession.ResponseStream<CocktailIdea>.Snapshot?) -> Cocktail? {
        var finalIngredients: [Ingredient] = []
        
        guard let name = cocktailIdea?.content.name else { return nil }
        guard let description = cocktailIdea?.content.description else { return nil }
        guard let ingredients = cocktailIdea?.content.ingredients else { return nil }
        guard let style = CocktailStyle(rawValue: cocktailIdea?.content.style ?? "short drink") else { return nil }
        guard let glass = CocktailGlass(rawValue: cocktailIdea?.content.glass ?? "highball") else { return nil }
        guard let mixingTechnique = CocktailMixingTechnique(rawValue: cocktailIdea?.content.mixingTechnique ?? "built") else { return nil }
        guard let difficulty = CocktailDifficulty(rawValue: cocktailIdea?.content.difficulty ?? "easy") else { return nil }
        
        for ingredient in ingredients {
            guard let ingredientName = ingredient.name else { return nil }
            guard let ingredientMeasure = ingredient.amount else { return nil }
            guard let ingredientUnit = Units(rawValue: ingredient.unit ?? "cl") else { return nil }
            
            let newIngredient = Ingredient(name: ingredientName, measure: String(ingredientMeasure), unit: ingredientUnit)
            finalIngredients.append(newIngredient)
            
        }
        return Cocktail(name: name, ingredients: finalIngredients, isPossible: true, style: style, glass: glass, mixingTechnique: mixingTechnique, difficulty: difficulty, cocktailDescription: description)
    }
}
