//
//  GetInspired.swift
//  BarTinder
//
//  Created by Mathis Gaignet on 02/07/2025.
//

import SwiftUI

/// A view that shows a cocktail generated by Foundation Models.
struct GetInspired: View {
    @Environment(GenerableModel.self) private var model
    @Environment(\.dismiss) private var dismiss
    @FocusState private var focus: Focus?
    
    @Binding var showNewIdeaSheet: Bool
    
    var body: some View {
        @Bindable var model = model
        
        ScrollView {
            VStack(alignment: .leading, spacing: 0) {
                HeaderMesh()
                    .overlay(alignment: .bottom) {
                        TitleHeader()
                            .padding(.bottom, 80)
                            .padding(.horizontal, 24)
                            .foregroundStyle(.white)
                    }
                
                if model.cocktailIdea != nil {
                    VStack(spacing: 20) {
                        InfosCard()
                        
                        if model.showButtons {
                            makeItYoursButton(model: model)
                            iDontLikeItButton
                        }
                    }
                    .animation(.easeIn, value: model.showButtons)
                    .padding(.vertical, 24)
                    .background(.regularMaterial, in: RoundedRectangle(cornerRadius: BarTinderApp.Padding.mainCornerRadius))
                    .padding(.horizontal)
                    .offset(y: -60)
                }
            }
        }
        .navigationBarBackButtonHidden()
        .ignoresSafeArea()
        .background(
            LinearGradient(
                stops: [
                    .init(color: .purple.opacity(0.1), location: 0.0),
                    .init(color: .purple.opacity(0.05), location: 0.9),
                    .init(color: .clear, location: 1.0)
                ],
                startPoint: .top,
                endPoint: .bottom
            )
        )
        .onAppear {
            model.cocktailIdea = nil
        }
        .alert("Violated guardrail", isPresented: $model.guardrailViolation) {
            Button("Ok", role: .cancel) {
                dismiss()
                showNewIdeaSheet = false
            }
        } message: {
            Text("You violated the guardrail of Apple Intelligence!")
        }
    }
}

#Preview {
    GetInspired(showNewIdeaSheet: .constant(true))
        .environment(PatchBay.patch.makeGenerableModel())
}




extension GetInspired {
    private func makeItYoursButton(model: GenerableModel) -> some View {
        Button {
            model.askedToCreate = true
            dismiss()
        } label: {
            Label("Make it yours", systemImage: "plus.circle.fill")
                .fontWeight(.semibold)
        }
        .buttonStyle(GenerateButton(color: .blue))
    }
    
    private var iDontLikeItButton: some View {
        Button {
            dismiss()
            model.showButtons = false
        } label: {
            Label("I don't like it", systemImage: "xmark.diamond")
        }
        .buttonStyle(GenerateButton(color: .red))
    }
}

private struct TitleHeader: View {
    @Environment(GenerableModel.self) private var model
    
    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            if let cocktailName = model.cocktailIdea?.name {
                Text(cocktailName)
                    .font(.system(size: 28, weight: .bold, design: .rounded))
                    .lineLimit(2)
                    .fixedSize(horizontal: false, vertical: true)
            } else {
                HStack(alignment: .top) {
                    Image(systemName: "sparkles")
                    Text("Crafting the best cocktail that fits your idea...")
                }
                .font(.system(size: 28, weight: .bold, design: .rounded))
            }
            
            if let cocktailDescription = model.cocktailIdea?.description {
                Text(cocktailDescription)
                    .font(.system(size: 15, weight: .regular, design: .default))
                    .lineLimit(4)
                    .fixedSize(horizontal: false, vertical: true)
                    .opacity(0.9)
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
    }
}

